### PR TITLE
UI tidy

### PR DESCRIPTION
**Pull request by commuterjoy**
Code still needs a damn good tidy, but this is a UI tweak before that.

### CODE REVIEW

**Comment by matthew-andrews** [comment]
how do you feel about putting `o-techdocs` on all our admin panels?

**Comment by matthew-andrews** [comment]
(no rush, but in principle)

**Comment by commuterjoy** [comment]
> how do you feel

sorta funny :)

**Comment by matthew-andrews** [comment]
funny is a positive feeling.

**Pull request merged**
